<a href="https://colab.research.google.com/github/W-Hailey/python_ML/blob/main/class04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

物件導向(Object oriented programming)


In [ ]:
#class後面第一個字一定要大寫(類別名稱)
class Person:
  def __init__(self):  # __init__:建構子(constructor)
    self.name="Hailey"
    self.gender="F"
    print("This is person class")



In [ ]:
p=Person() #物件化(實體化) instance
#類別實體化->物件

In [ ]:
class Person:
  #def __init__:建構子(constructor)
  def __init__(self,name,gender): 
    self.n=name
    self.g=gender
    print("This is person class")
  #instance method   
  def introduction(self):  #method一定要寫在class裡
    print(f"Hellow my name is{self.n}")

p1=Person(name="Hailey", gender="F")
p2=Person(name="Tom", gender="M")

This is person class
This is person class


In [ ]:
print(p1.n, p1.g)
print(p2.n, p2.g)

Hailey F
Tom M


In [ ]:
p1.introduction() #instance method
p2.introduction()

Hellow my name isHailey
Hellow my name isTom


In [ ]:
#物件屬性attribute寫在__init__裡面
class Warrior:
  def __init__(self,name,gender, weapon="bat"): 
    #共同屬性
    self.lv = 1
    self.exp = 0
    #客製化屬性
    self.n = name
    self.g = gender
    self.w = weapon
    print("This is Warrior class.")
  def __str__(self): #__str__(self)***
    return f"Name:{self.n},Gender:{self.g},Weapon:{self.w},Level:{self.lv},EXP:{self.exp}"
  
  #def attack(self):
      #self.exp += 40 #每次攻擊時 經驗值加40
      #if self.exp >= 100:
        #self.lv+=1
        #self.exp-=100
      #print(f"{self.n} attacked! Level: {self.lv}, Exp: {self.exp}")

  def attack(self,enemy):
    self.exp += 40 #每次攻擊時 經驗值加40
    enemy.hp -= 1  
    self.level_up()
    print(f"{self.n} attacked! Level: {self.lv}, Exp: {self.exp}")
  
  def level_up(self):
    if self.exp >= 100:
      self.lv+=1
      self.exp-=100
      print(f"{self.n} level up!!!")

In [ ]:
class Enemy: #定義enemy
  def __init__(self):
    self.name="Monster"
    self.hp=100

In [ ]:
e1=Enemy()

In [ ]:
w1=Warrior(name="Thousand", gender="Male",weapon="Sword")
w2=Warrior(name="Allie", gender="Female",weapon="Longbow")


This is Warrior class.
This is Warrior class.


In [ ]:
print(f"Warrior:{w1}")

Warrior:Name:Thousand,Gender:Male,Weapon:Sword,Level:1,EXP:0


In [ ]:
for i in range(5):
  w1.attack() 

Thousand attacked! Level: 3, Exp: 40
Thousand attacked! Level: 3, Exp: 80
Thousand level up!!!
Thousand attacked! Level: 4, Exp: 20
Thousand attacked! Level: 4, Exp: 60
Thousand level up!!!
Thousand attacked! Level: 5, Exp: 0


繼承(inherit)

In [ ]:
class Character: #爸爸
  def __init__(self,name, gender, weapon="bat"):
    self.lv = 1
    self.exp = 0
    self.n = name
    self.g = gender
    self.w = weapon
    print("This is a Character class.")
  def __str__(self): #__str__(self)***
    return f"Name:{self.n},Gender:{self.g},Weapon:{self.w},Level:{self.lv},EXP:{self.exp}"
  
  def attack(self,enemy):
    self.exp += 40 #每次攻擊時 經驗值加40
    enemy.hp -= 1  
    self.level_up()
    print(f"{self.n} attacked! Level: {self.lv}, Exp: {self.exp}")
  
  def level_up(self):
    if self.exp >= 100:
      self.lv+=1
      self.exp-=100
      print(f"{self.n} level up!!!")
 

In [ ]:
class Enemy: #定義enemy
  def __init__(self):
    self.name="Monster"
    self.hp=100

In [ ]:
class Warrior(Character): #兒子
  def __init__(self, name, gender, weapon="bat"):
    super().__init__(name, gender, weapon) #super():呼叫爸爸
    self.sp=100
    print("This is Warrior Class")
  def attack(self,enemy):  #爸爸attack做完，再新增自己做的
    super().attack(enemy)
    print("w1")

  



In [ ]:
class Magician(Character): #兒子
  def __init__(self, name, gender, weapon="bat"):
    super().__init__(name, gender, weapon)
    self.mp=100
    print("This is Magician Class")

In [ ]:
e1=Enemy()

In [ ]:
w1=Warrior(name="Thousand",gender="Male",weapon="Sword")

This is a Character class.
This is Warrior Class


In [ ]:
for i in range(5):
  w1.attack(enemy=e1) 

Thousand attacked! Level: 1, Exp: 40
w1
Thousand attacked! Level: 1, Exp: 80
w1
Thousand level up!!!
Thousand attacked! Level: 2, Exp: 20
w1
Thousand attacked! Level: 2, Exp: 60
w1
Thousand level up!!!
Thousand attacked! Level: 3, Exp: 0
w1


numpy

In [ ]:
import numpy as np


In [ ]:
a=[1,2,3]
b=[4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [ ]:
arr1=np.array(a)
arr2=np.array(b)
print(arr1+arr2)

[5 7 9]


In [ ]:
# numpy basic
a = np.array([1,2,3])
b = np.array([[1.0,2.0,3.0],[3.2,5.7,8.2]])
print(f"a: {a}")
print(f"a dimension: {a.ndim}")
print(f"a shape: {a.shape}") #shape: (幾個row，幾個col)
print(f"a type: {a.dtype}")
print(f"b: {b}")
print(f"b dimension: {b.ndim}")
print(f"b shape: {b.shape}") #(2,3):兩筆資料(兩個框框)，三個切片(最裡面框框有幾個數字)
print(f"b type: {b.dtype}")

In [ ]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a[1,2]) # 9
print(a[0,:]) # 第一個全部 [1,2,3,4,5,6]
print(a[:,2]) # 所有的第二個 [3,9]
print(a[0,1:5:2]) # [2,4] (start,stop,step)
a[1,2] = 20
print(a)
a[:,2] = [7,8]
print(a)

9
[1 2 3 4 5 6]
[3 9]
[2 4]
[[ 1  2  3  4  5  6]
 [ 7  8 20 10 11 12]]
[[ 1  2  7  4  5  6]
 [ 7  8  8 10 11 12]]


In [ ]:
a = np.array([[[1,2],[3,5],[7,8]],
              [[1,7],[-3,2],[10,2]],
              [[6,-2],[5,-3],[7,9]],
              [[8,5],[-2,2],[26,-2]],
              [[1,-7],[-3,2],[-5,-2]],])
print(a)
print(a.shape) 
print(a[3,2,0])
print(a[:,1,:])

[[[ 1  2]
  [ 3  5]
  [ 7  8]]

 [[ 1  7]
  [-3  2]
  [10  2]]

 [[ 6 -2]
  [ 5 -3]
  [ 7  9]]

 [[ 8  5]
  [-2  2]
  [26 -2]]

 [[ 1 -7]
  [-3  2]
  [-5 -2]]]
(5, 3, 2)
26
[[ 3  5]
 [-3  2]
 [ 5 -3]
 [-2  2]
 [-3  2]]


In [ ]:
# list: 用來存放，用numpy算(不要用list算)

In [ ]:
# 乘法單位元素
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
identity = np.identity(3) #np.identity(3): 3*3單位矩正
print(np.matmul(a,identity))

In [ ]:
# statistics
a = np.array([[92,83,56,77,98],[81,53,64,76,60]])
print(np.max(a))
#axis***
print(np.max(a,axis=0)) #找直向最大 (2選一)
print(np.max(a,axis=1)) #找橫向最大 (兩組裡面個別最大值)
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

98
[92 83 64 77 98]
[98 81]
[173 136 120 153 158]
[406 334]
